/* UTech CTF Hub - Data (Challenges, Tracks, Quizzes, Leaderboard, Jeopardy) */
/* ========================================================================== */

// ── DATA (no raw HTML tags inside strings) ────────────────────
var TRACKS = [
  {icon:'🔐',title:'Cryptography',diff:'beginner',progress:60,challenges:3,
   desc:'Ciphers, Base64, ROT13, Vigenere, and intro RSA concepts.',
   bullets:['Understand symmetric vs asymmetric encryption','Base64 is encoding, not encryption','ROT13 is a Caesar cipher with shift of 13','Hashing is one-way — MD5/SHA family','Frequency analysis breaks simple substitution ciphers','Vigenere cipher uses a repeating key','Salt prevents rainbow table attacks on hashes','XOR is used in many stream ciphers','Binary, hex, ASCII are common encoding formats','RSA relies on difficulty of factoring large primes'],
   examples:['Base64("Hello") = SGVsbG8=','ROT13("FLAG") = SYNT','MD5 collisions possible but SHA-256 is strong'],
   quizzes:[{q:'What does Base64 do?',opts:['Encrypts data','Encodes binary as text','Hashes passwords','Compresses files'],a:1},{q:'Which is a one-way function?',opts:['Base64','XOR','SHA-256','Caesar cipher'],a:2}],
   recs:["Caesar's Secret","Base64 Decode","Vigenere Cipher"]},
  {icon:'🌐',title:'Web Security',diff:'intermediate',progress:40,challenges:4,
   desc:'SQL injection, XSS, IDOR logic flaws, OWASP Top 10.',
   bullets:['SQL injection manipulates database queries','XSS injects scripts into victim browsers','IDOR lets you access unauthorized resources','CSRF tricks authenticated users into actions','Use parameterized queries to prevent SQLi','Content Security Policy mitigates XSS','Always validate input server-side not just client-side','HTTP-only cookies prevent JS cookie theft','HTTPS is transport security not application security','OWASP Top 10 is the go-to web vulnerability reference'],
   examples:["SQLi bypass: ' OR '1'='1' --","XSS payload: alert(document.cookie)","IDOR: change ?user_id=1234 to ?user_id=1235"],
   quizzes:[{q:'What does SQLi exploit?',opts:['JavaScript','HTTP headers','Database queries','Session tokens'],a:2},{q:'XSS stands for?',opts:['Cross-Site Scripting','Cross-Server Syntax','Cross-Session Security','Cross-Site Sessions'],a:0}],
   recs:['SQL Injection 101','XSS Playground','IDOR Logic Flaw']},
  {icon:'🔎',title:'Forensics',diff:'beginner',progress:30,challenges:3,
   desc:'File carving, steganography, PCAP analysis, metadata.',
   bullets:['Steganography hides data inside other files','File headers (magic bytes) identify true file types','Metadata in images includes GPS and timestamps','PCAP files capture raw network traffic','Wireshark is the standard PCAP analysis tool','Hex editors reveal hidden data in files','LSB steganography hides bits in image pixels','Deleted files can often be recovered','Zip files can contain password-protected content','Linux strings command extracts readable text from binaries'],
   examples:['file image.png reveals JPEG disguised as PNG','strings secret.bin | grep CTF','binwalk firmware.bin extracts hidden files'],
   quizzes:[{q:'What tool reads PCAP files?',opts:['Nmap','Burp Suite','Wireshark','Metasploit'],a:2},{q:'LSB steganography hides data in?',opts:['File headers','Least significant bits','DNS records','HTTP cookies'],a:1}],
   recs:['Hidden in Plain Sight','PCAP Protocol Hunt','Metadata Mystery']},
  {icon:'⚙️',title:'Reverse Engineering',diff:'intermediate',progress:20,challenges:3,
   desc:'Disassembly, string extraction, basic crackmes.',
   bullets:['Decompilers convert binary back to readable code','strings command extracts human-readable text from binaries','Ghidra and IDA are popular RE frameworks','x86 assembly: mov, push, pop, call, ret, jmp, cmp','Function prologues: push ebp then mov ebp esp','XOR decryption is common in simple obfuscation','Packing compresses and obfuscates executables','ELF is the Linux binary format PE is Windows','Dynamic analysis runs the binary in a controlled env','Static analysis does not execute the file'],
   examples:['strings crackme | grep -i flag','objdump -d binary | head -50','Ghidra: File Import then Analyze'],
   quizzes:[{q:'Which tool extracts strings from a binary?',opts:['grep','strings','cat','hexdump'],a:1},{q:'ELF is the binary format for?',opts:['Windows','macOS','Linux','Android'],a:2}],
   recs:['Crackme v1','String Hunt','Encoded Logic']},
  {icon:'📡',title:'Network Security',diff:'intermediate',progress:25,challenges:3,
   desc:'Protocols, ports, PCAP analysis, scanning basics.',
   bullets:['TCP three-way handshake: SYN SYN-ACK ACK','Common ports: 80 HTTP 443 HTTPS 22 SSH 21 FTP','UDP is connectionless — no handshake','DNS resolves domain names to IP addresses','ARP maps IP addresses to MAC addresses','Nmap is the industry standard port scanner','Sniffing captures packets on a network segment','Firewalls filter traffic by port or IP or protocol','VLANs segment network traffic logically','TLS/SSL encrypts data in transit'],
   examples:['nmap -sV 192.168.1.1 (version scan)','TCP SYN scan: nmap -sS (stealth scan)','Wireshark filter: http.request.method == GET'],
   quizzes:[{q:'Port 443 is used by?',opts:['FTP','HTTP','HTTPS','SSH'],a:2},{q:'What does DNS do?',opts:['Encrypts traffic','Resolves domain names','Filters packets','Assigns IP addresses'],a:1}],
   recs:['PCAP Protocol Hunt','Port Scan Analysis','Network Map Reasoning']},
  {icon:'🕵️',title:'Social Engineering',diff:'beginner',progress:50,challenges:3,
   desc:'Phishing identification, pretexting scenarios, awareness.',
   bullets:['Phishing uses fake emails to steal credentials','Spear phishing is targeted at specific individuals','Pretexting creates a fabricated scenario to extract info','Vishing is voice phishing over phone calls','Urgency and fear are common manipulation tactics','Check sender email address carefully not just display name','Hover over links before clicking to see real URL','HTTPS does not mean a site is safe — only that it is encrypted','Two-factor authentication limits phishing damage','Security awareness training reduces click rates significantly'],
   examples:['From: support@paypa1.com (note the number 1)','Subject: URGENT: Verify your account NOW','Link text shows paypal.com but URL goes elsewhere'],
   quizzes:[{q:'Spear phishing targets?',opts:['Random users','Specific individuals','Only executives','Only companies'],a:1},{q:'What does vishing use?',opts:['Email','SMS','Voice calls','Fake websites'],a:2}],
   recs:['Spot the Phish','Pretexting Scenario','CEO Fraud Analysis']}
];

var CHALLENGES = [
  {id:1,title:'SQL Injection 101',cat:'web',diff:'beginner',pts:100,desc:'Bypass a login form using classic SQL injection.',scenario:"You have found a login page at /admin. The developer did not sanitize inputs. Can you get in without a valid password?",files:[{name:'login_page.html',size:'4.2 KB'}],flag:'CTF{sql1_b4s1cs_bypass}',hint:"Try entering: ' OR '1'='1' -- as the username",learned:['How SQL queries are constructed','Why parameterized queries prevent injection','The importance of input sanitization'],solves:38,solved:true},
  {id:2,title:"Caesar's Secret",cat:'crypto',diff:'beginner',pts:75,desc:'Decode an encrypted message using frequency analysis.',scenario:'An intercepted message reads: GUR SYNt VF: PGS{ebg13_vf_rnfl}. The sender always uses the same simple cipher.',files:[],flag:'CTF{rot13_is_easy}',hint:'This cipher shifts each letter by 13 positions.',learned:['ROT13 and Caesar cipher mechanics','Frequency analysis basics','Why simple ciphers are insecure'],solves:42,solved:false},
  {id:3,title:'Hidden in Plain Sight',cat:'forensics',diff:'beginner',pts:150,desc:'A PNG file contains a hidden flag. Find it.',scenario:'You received an image from an anonymous source. The flag is hidden using steganography. The image appears normal at first glance.',files:[{name:'suspicious.png',size:'1.8 MB'}],flag:'CTF{lsb_steg0_f0und}',hint:'Try steghide or examine the least significant bits of each pixel.',learned:['LSB steganography technique','Using steghide and zsteg tools','File format internals'],solves:27,solved:false},
  {id:4,title:'Crackme v1',cat:'reverse',diff:'intermediate',pts:200,desc:'This binary asks for a password. Find it using reverse engineering.',scenario:'A small Linux binary checks your input against a hardcoded password. Use static analysis tools to extract it without running the program.',files:[{name:'crackme',size:'12 KB'},{name:'README.txt',size:'512 B'}],flag:'CTF{r3v3rs3d_p4ssw0rd}',hint:'Try running strings on the binary and look for something that looks like a password.',learned:['Using the strings command','Basic static binary analysis','How passwords can be stored insecurely in binaries'],solves:19,solved:false},
  {id:5,title:'XSS Playground',cat:'web',diff:'intermediate',pts:125,desc:'Inject a script into an unfiltered comment field.',scenario:'A training web app has a comment section that reflects user input without sanitization. Inject a payload that triggers an alert with the session cookie.',files:[],flag:'CTF{xss_r3fl3ct3d_c00k13}',hint:'Try injecting: alert(document.cookie) via a script tag in the comment box.',learned:['Reflected vs stored XSS','Cookie theft via XSS','Content Security Policy as mitigation'],solves:31,solved:false},
  {id:6,title:'PCAP Protocol Hunt',cat:'network',diff:'beginner',pts:100,desc:'Identify the hidden flag inside a network capture.',scenario:'A network capture was taken during a CTF event. Somewhere in the HTTP traffic a flag was transmitted in plaintext. Can you find it?',files:[{name:'traffic.pcap',size:'340 KB'}],flag:'CTF{pcap_h1dd3n_fl4g}',hint:'Filter Wireshark by HTTP and look at the request and response bodies.',learned:['Using Wireshark for packet analysis','HTTP traffic is cleartext','Importance of HTTPS'],solves:35,solved:false},
  {id:7,title:'Spot the Phish',cat:'social',diff:'beginner',pts:75,desc:'Analyze an email and identify all phishing red flags.',scenario:'You receive a suspicious email claiming to be from your bank. Analyze the headers, sender address, links, and language to identify every red flag.',files:[{name:'phishing_email.txt',size:'2.1 KB'}],flag:'CTF{ph1sh1ng_4w4r3ness}',hint:'Check: sender domain, urgency language, mismatched URLs, spelling errors.',learned:['Email header analysis','Common phishing indicators','URL spoofing techniques'],solves:44,solved:true},
  {id:8,title:'Vigenere Cipher',cat:'crypto',diff:'intermediate',pts:175,desc:'Break a Vigenere cipher using known-plaintext attack.',scenario:'An encrypted message was intercepted. You know the first word of the plaintext is ATTACK. Use this to recover the key and decrypt the full message.',files:[{name:'ciphertext.txt',size:'1 KB'}],flag:'CTF{v1g3n3r3_k3y_r3c0v3r3d}',hint:'Use the known plaintext to XOR and recover repeating key segments.',learned:['How Vigenere encryption works','Known-plaintext attacks','Index of Coincidence for key length estimation'],solves:14,solved:false},
  {id:9,title:'Blind SQLi Sim',cat:'web',diff:'advanced',pts:400,desc:'Extract data from a database without visible output.',scenario:'The target endpoint does not show database errors but boolean-based inference still works. Use systematic true/false queries to extract the flag character by character.',files:[],flag:'CTF{bl1nd_sql1_ch4r_by_ch4r}',hint:"Use SUBSTRING on a SELECT query and test each character one by one with boolean conditions.",learned:['Boolean-based blind SQL injection','Automated extraction with SQLMap','Why error suppression is not a real security fix'],solves:8,solved:false},
  {id:10,title:'RSA Puzzle',cat:'crypto',diff:'advanced',pts:350,desc:'Solve a guided RSA problem with small primes.',scenario:'You intercepted RSA-encrypted data with very small public key parameters (n=3233, e=17). Factor n to find p and q, compute the totient, then find d and decrypt.',files:[{name:'rsa_params.txt',size:'512 B'}],flag:'CTF{rs4_sm4ll_n_f4ct0r3d}',hint:'n=3233=61x53. Compute phi(n)=(p-1)(q-1). Find d such that e*d is congruent to 1 mod phi(n).',learned:['RSA key generation steps','Why small primes are catastrophically weak','Extended Euclidean Algorithm for modular inverse'],solves:6,solved:false},
  {id:11,title:'Stack Overflow',cat:'reverse',diff:'advanced',pts:400,desc:'Exploit a buffer overflow to redirect execution.',scenario:'A vulnerable C program reads user input into a fixed buffer with no bounds checking. Overwrite the return address to jump to the win() function.',files:[{name:'vuln',size:'8 KB'},{name:'vuln.c',size:'1.2 KB'}],flag:'CTF{buff3r_0v3rfl0w_pwnd}',hint:'Find the offset to EIP using a cyclic pattern. win() is at address 0x08048456.',learned:['Stack memory layout','Return address overwriting','GDB for dynamic analysis'],solves:5,solved:false},
  {id:12,title:'Pretexting Scenario',cat:'social',diff:'advanced',pts:300,desc:'Identify the safest responses in a multi-step social engineering attack.',scenario:'A new IT employee calls asking for your login to test connectivity. Then they follow up via email. Then they escalate to your manager. Identify the best security-aware response at each step.',files:[{name:'scenario_transcript.txt',size:'3 KB'}],flag:'CTF{s0c_eng_4w4r3_r3sp0ns3}',hint:'At each step ask: does legitimate IT ever need your password?',learned:['Pretexting and authority exploitation','Verification procedures','When to escalate to a supervisor'],solves:11,solved:false}
];

var LEADERBOARD=[
  {rank:1,name:'0xGh0st',pts:4820,solves:38,you:false},
  {rank:2,name:'null_ptr',pts:4225,solves:34,you:false},
  {rank:3,name:'bytebender',pts:3900,solves:31,you:false},
  {rank:4,name:'r3v3rs3r',pts:3450,solves:28,you:false},
  {rank:5,name:'cr4ckh4x0r',pts:2875,solves:23,you:false},
  {rank:6,name:'pwnmaster99',pts:2100,solves:17,you:false},
  {rank:7,name:'jdoe',pts:1337,solves:12,you:true},
  {rank:8,name:'sec_learner',pts:950,solves:9,you:false},
  {rank:9,name:'hackstart',pts:600,solves:6,you:false},
  {rank:10,name:'newbie01',pts:275,solves:3,you:false}
];

var JCATS=['Web','Crypto','Network','Linux','OWASP','Incident'];
var JQ={
  Web:{100:{q:'What does SQL stand for?',opts:['Structured Query Language','Simple Query Logic','Secure Query Layer','System Query Language'],a:0},200:{q:'Which HTTP method submits form data?',opts:['GET','DELETE','POST','PUT'],a:2},300:{q:'What vulnerability injects scripts into web pages?',opts:['SQLi','CSRF','XSS','SSRF'],a:2},400:{q:'IDOR stands for?',opts:['Insecure Direct Object Reference','Internal Data Object Redirect','Insecure Data Output Read','Internal Directory Object Request'],a:0},500:{q:'Which header prevents clickjacking?',opts:['X-XSS-Protection','X-Frame-Options','Content-Type','Strict-Transport-Security'],a:1}},
  Crypto:{100:{q:'Base64 is a type of what?',opts:['Encryption','Hashing','Encoding','Compression'],a:2},200:{q:'Which algorithm produces a 256-bit hash?',opts:['MD5','SHA-1','SHA-256','AES'],a:2},300:{q:'What is a salt in password hashing?',opts:['An encryption key','Random data added before hashing','A type of cipher','A password policy'],a:1},400:{q:'RSA security relies on?',opts:['Discrete logarithm','Factoring large primes','XOR operations','Symmetric keys'],a:1},500:{q:'Which cipher uses a Feistel network?',opts:['AES','RSA','DES','ECC'],a:2}},
  Network:{100:{q:'What port does HTTP use?',opts:['443','8080','21','80'],a:3},200:{q:'TCP handshake sequence?',opts:['SYN-ACK-FIN','SYN-SYN/ACK-ACK','ACK-SYN-ACK','FIN-SYN-ACK'],a:1},300:{q:'What does ARP do?',opts:['Resolves IP to MAC','Encrypts traffic','Routes packets','Assigns IPs'],a:0},400:{q:'Which is the stealth scan flag in nmap?',opts:['-sV','-sS','-sU','-A'],a:1},500:{q:'What protocol does DNS use by default?',opts:['TCP only','UDP only','Both TCP and UDP','HTTPS'],a:2}},
  Linux:{100:{q:'Command to list directory files?',opts:['dir','list','ls','show'],a:2},200:{q:'Command to show running processes?',opts:['top','run','proc','task'],a:0},300:{q:'Permission 777 means?',opts:['Read only for all','No permissions','Full permissions for all','Owner full others read'],a:2},400:{q:'What does chmod +x do?',opts:['Delete file','Make file executable','Copy file','Move file'],a:1},500:{q:'Which command finds files by name recursively?',opts:['search','locate','find','grep -r'],a:2}},
  OWASP:{100:{q:'OWASP stands for?',opts:['Open Web Application Security Project','Online Web App Security Protocol','Open Website Application Standard Policy','Operational Web App Security Platform'],a:0},200:{q:'Number 1 risk in OWASP Top 10 2021?',opts:['Cryptographic Failures','Injection','Broken Access Control','SSRF'],a:2},300:{q:'What is SSRF?',opts:['Server-Side Request Forgery','Same-Site Resource Failure','Session Security Request Flaw','Server Script Remote Function'],a:0},400:{q:'Insecure deserialization can lead to?',opts:['Slow performance','Remote code execution','Database exposure','CSS injection'],a:1},500:{q:'Security Logging is in OWASP Top 10 because?',opts:['Logging uses too much RAM','Breaches go undetected without it','Logs expose passwords','Monitoring prevents all attacks'],a:1}},
  Incident:{100:{q:'First step in incident response?',opts:['Eradication','Identification','Containment','Recovery'],a:1},200:{q:'IOC stands for?',opts:['Incident of Crime','Indicator of Compromise','Internet of Control','Internal Operational Command'],a:1},300:{q:'SIEM stands for?',opts:['Security Incident and Event Management','System Identification and Event Monitor','Secure Infrastructure Event Manager','Security Information and Event Management'],a:3},400:{q:'Chain of custody is important for?',opts:['System performance','Legal evidence integrity','Password resets','Network uptime'],a:1},500:{q:'Forensic imaging creates?',opts:['A virus scan','A backup','A bit-for-bit copy of storage','A network capture'],a:2}}
};

var QUIZZES=[
  {id:1,icon:'🌐',title:'OWASP Top 10 Basics',desc:'Test your knowledge of the most critical web security risks.',pts:100,questions:[
    {q:'What does XSS stand for?',opts:['Cross-Site Scripting','Cross-Server Security','Cross-System Session','Cross-Site Sessions'],a:0,exp:'XSS allows attackers to inject malicious scripts into web pages viewed by other users.'},
    {q:'Which vulnerability allows SQL commands to be injected?',opts:['XSS','CSRF','SQL Injection','IDOR'],a:2,exp:'SQL Injection manipulates database queries through unsanitized user input.'},
    {q:'CSRF attack tricks a user into?',opts:['Visiting a phishing site','Performing unwanted actions while authenticated','Downloading malware','Revealing their password'],a:1,exp:'CSRF exploits the trust a site has in an authenticated user.'},
    {q:'Number 1 risk in OWASP Top 10 2021?',opts:['Injection','Broken Authentication','Broken Access Control','Security Misconfiguration'],a:2,exp:'Broken Access Control moved to number 1 in the 2021 OWASP Top 10.'},
    {q:'IDOR is a type of?',opts:['Injection','Access Control Vulnerability','Cryptographic Failure','Logging Issue'],a:1,exp:'IDOR is an access control flaw where users can access unauthorized resources.'},
    {q:'Parameterized queries prevent which attack?',opts:['XSS','CSRF','SQL Injection','Clickjacking'],a:2,exp:'Parameterized queries separate SQL code from data, preventing injection.'},
    {q:'Content-Security-Policy header helps prevent?',opts:['SQLi','CSRF','XSS','IDOR'],a:2,exp:'CSP restricts which scripts can be loaded, mitigating XSS.'},
    {q:'Which is NOT in the OWASP Top 10 2021?',opts:['SSRF','Cryptographic Failures','Insecure Direct Object Reference','Vulnerability Scanning'],a:3,exp:'Vulnerability Scanning is a practice, not a vulnerability class.'},
    {q:'Security logging is important because?',opts:['It speeds up apps','Breaches go undetected without it','It prevents all attacks','It replaces firewalls'],a:1,exp:'Without proper logging, attackers can persist undetected for months.'},
    {q:'Secure by design means?',opts:['Using HTTPS only','Adding security after deployment','Building security in from the start','Having a security team'],a:2,exp:'Secure by design means security is built in from the very beginning.'}
  ]},
  {id:2,icon:'🔐',title:'Cryptography Fundamentals',desc:'Hashing, encryption, encoding, and real-world crypto concepts.',pts:100,questions:[
    {q:'SHA-256 is a?',opts:['Symmetric cipher','Hash function','Asymmetric cipher','Encoding scheme'],a:1,exp:'SHA-256 is a cryptographic hash function producing a 256-bit digest.'},
    {q:'Which is reversible?',opts:['MD5 hash','AES encryption','SHA-256 hash','bcrypt hash'],a:1,exp:'AES encryption is reversible with the correct key. Hash functions are one-way.'},
    {q:'What does a salt do in password hashing?',opts:['Makes hashing faster','Prevents rainbow table attacks','Encrypts the hash','Compresses the password'],a:1,exp:'A salt is random data added before hashing, making rainbow tables useless.'},
    {q:'RSA is an example of?',opts:['Symmetric encryption','Hashing','Asymmetric encryption','Stream cipher'],a:2,exp:'RSA uses a public key to encrypt and a private key to decrypt.'},
    {q:'Base64 increases data size by approximately?',opts:['10%','25%','33%','50%'],a:2,exp:'Base64 encodes 3 bytes as 4 characters, increasing size by about 33%.'},
    {q:'Which is the weakest password storage method?',opts:['bcrypt','SHA-256 with salt','MD5 without salt','Argon2'],a:2,exp:'MD5 without salt is vulnerable to rainbow table attacks and is very fast to crack.'},
    {q:'AES stands for?',opts:['Advanced Encryption Standard','Asymmetric Encryption System','Authenticated Encoding Service','Algorithmic Encryption Scheme'],a:0,exp:'AES is a widely used symmetric block cipher.'},
    {q:'Public key cryptography uses?',opts:['One key for everything','Two mathematically linked keys','A shared secret','Random keys each session'],a:1,exp:'Public key crypto uses a public key and a private key that are mathematically linked.'},
    {q:'Which cipher is the simplest to break?',opts:['AES-256','Caesar cipher','RSA','ChaCha20'],a:1,exp:'The Caesar cipher only has 25 possible keys, easily brute-forced.'},
    {q:'TLS provides?',opts:['Authentication only','Encryption only','Both encryption and authentication','Neither'],a:2,exp:'TLS provides both encryption and authentication.'}
  ]},
  {id:3,icon:'📡',title:'Network Security Essentials',desc:'Protocols, ports, scanning, and network defense fundamentals.',pts:100,questions:[
    {q:'Port 22 is used by?',opts:['HTTP','FTP','SSH','Telnet'],a:2,exp:'Port 22 is the default for SSH, used for encrypted remote administration.'},
    {q:'TCP is different from UDP because TCP is?',opts:['Faster','Connectionless','Connection-oriented','Encrypted'],a:2,exp:'TCP uses a three-way handshake and guarantees delivery. UDP is connectionless.'},
    {q:'DNS translates?',opts:['IP to MAC','Domain names to IP addresses','Ports to services','HTTP to HTTPS'],a:1,exp:'DNS resolves human-readable domain names to IP addresses.'},
    {q:'A firewall primarily filters traffic based on?',opts:['File content','IP addresses and ports','User behavior','Encryption strength'],a:1,exp:'Traditional firewalls filter traffic based on IP addresses, ports, and protocols.'},
    {q:'What does nmap do?',opts:['Cracks passwords','Scans networks for open ports','Analyzes PCAP files','Decrypts SSL traffic'],a:1,exp:'Nmap is a network scanner that discovers hosts and open ports.'},
    {q:'Which is a private IP range?',opts:['8.8.8.8','172.16.0.0/12','54.239.28.85','203.0.113.0'],a:1,exp:'172.16.0.0/12 is one of three private IP address ranges defined in RFC 1918.'},
    {q:'ARP spoofing enables which attack?',opts:['SQL injection','Man-in-the-middle','Buffer overflow','XSS'],a:1,exp:'ARP spoofing poisons the ARP cache to intercept traffic between hosts.'},
    {q:'HTTPS uses which port by default?',opts:['80','8080','443','8443'],a:2,exp:'HTTPS uses port 443 by default.'},
    {q:'A packet sniffer captures?',opts:['Keystrokes','Network packets','Log files','Memory dumps'],a:1,exp:'A packet sniffer like Wireshark captures and analyzes network traffic.'},
    {q:'VLAN is used to?',opts:['Speed up routing','Segment network traffic logically','Encrypt traffic','Assign IP addresses'],a:1,exp:'VLANs logically separate network segments, improving security and reducing broadcast domains.'}
  ]}
];